### ISSUE TITLE
problem creating an account

### ISSUE THREAD

**Issue by anybany** [MrAshTonka/contact-form#1]
Hi, after i created a new database in phpmyadmin and set the password in init.php the contact form shows up.

but when i fill and send it i get an error: There was a problem creating an account

i am not quite sure what to do from here. do i have to create a table in phpmyadmin first?

update: so i just imported your form.sql file. now i've got the alle 7 tables but still get the error

update2: okay i found at that it wasn't possible to create a new user because your .sql file does not create the tables budget, phone etc. so i just deleted these from the user create function and the html form. now the mail is delivered and a new user shows up in the database. but there is no success notification anymore and the site weirdly reloads. any idea? :D

**Comment by MrAshTonka** [comment]
Hey, you didn't have to delete anything. 

Make sure your table name is the same as mine or you'll need to change it in User.php (can't remember the line number) but you'll see it will spit out the error message if wrong as it won't be able to write to the database.

I don't think I ever made a success message pop up once completed either that would be why it weirdly reloads if anything.

**Comment by anybany** [comment]
oh sorry, i tested so many contact forms yesterday, i must have mixed it up a little :D 
could you help me to make a ajax success message for your form?

**Comment by Zeaphon** [comment]
Hi, I still have some problems with this, I set everything up and get the same error as anybany. What table name would it be and what should I change it into?

I haven't changed any other structure of your files yet.

**Comment by MrAshTonka** [comment]
Inside User.php you'll need to change the database name to what your database is called

**Comment by Zeaphon** [comment]
Thanks for the information, but apparently I'm not very good at this and I just can't figure out where to put my database name, since there is no previous database name active. I have everything set in init.php, but can't find the right entry.

**Comment by MrAshTonka** [comment]
public function create($fields = array()) {
		if(!$this->_db->insert('form', $fields)) { //THIS LINE
			throw new Exception('There was a problem creating an account');
		}
	}

You will need to change 'form' to your database table name within User.php line 13
